### ISSUE TITLE
Question on GetSharedFilePermissions function

### ISSUE THREAD

**Issue by Delsk** [smcavinue/AdminSeanMc#1]
Shouldn't the "return" on line 281 be outside the foreach on line 271

https://github.com/smcavinue/AdminSeanMc/blob/49e5280273a6e26fdeefaf84675c642e22843a00/Graph%20Scripts/graph-OneDrive-External-Sharing-Report.ps1#L281

**Comment by smcavinue** [comment]
Nice catch - resolved now!
