### ISSUE TITLE
Question on graph-PopulateContactsFromCSV

### ISSUE THREAD

**Issue by nldenic** [smcavinue/AdminSeanMc#2]
Hi,

Could we also schedule this so it will run every week for every user that is enabled ?

Or better Export Csv automatically and import to the contact > Subfolder ( Company Contacts )

Do you think this is possible ? This will be realy good sollution for some softwares like Cirasync or GALSync.

**Comment by smcavinue** [comment]
Hi,
Yes scheduling would not be a problem, just call it weekly from Azure automation or a scheduled task
