### ISSUE TITLE
No Mailbox Stats

### ISSUE THREAD

**Issue by PHARKETT** [smcavinue/AdminSeanMc#3]
When I run the script it does not populate the mailbox stats into the spreadsheet but I can see them in $MailboxStatsReport

I'm not a powershell expert but will this line work as the userprincipalname in the stats is a guid and a name in the $users?
    $stats = $MailboxStatsReport | ? { $_.'User Principal Name' -eq $user.userprincipalname }

User Principal Name                : F4A03F10147176D455A66FE7FA72363C
userPrincipalName         : PattiF@xxxxxxxx.OnMicrosoft.com

**Comment by smcavinue** [comment]
You need to make sure that anonymized reporting is disabled, if the usernames are still showing as obfuscated.
