### ISSUE TITLE
Doubt about the Prepare-TenanataAssessment.ps1 script

### ISSUE THREAD

**Issue by Duzima** [smcavinue/AdminSeanMc#4]
Script Prepare-TenanatAssessment.ps1
Line 187

$Thumbprint = New-AadApplicationCertificate -ClientId $appReg.AppId -CertificatePassword "T3mPP@£6hnhskke!!!" -AddToApplication -certificatename "Tenant Assessment Certificate"

On line 187 we have a password for the certificate, can we change it?

Thanks for the scripts, they are very useful!

**Comment by smcavinue** [comment]
Yes you can absolutely change it to anything you like or add it as a parameter!
