### ISSUE TITLE
Invoke-RestMethod : The remote server returned an error: (401) Not authorized.

### ISSUE THREAD

**Issue by Duzima** [smcavinue/AdminSeanMc#6]
The script is generating the following output after approximately one hour of execution. It generates the error but keeps trying.

![PS1](https://user-images.githubusercontent.com/80268174/181308302-ffa3813f-96f0-4a21-ba66-0d2e15da4e23.png)

**Comment by smcavinue** [comment]
Not authorized would generally point at permissions not in place, have you checked permissions are set up correctly?
