### ISSUE TITLE
Shared Folders are omitted

### ISSUE THREAD

**Issue by Delsk** [smcavinue/AdminSeanMc#7]
I've been doing some work on a script, using yours as the foundation. I noticed something that I think might be a problem. Your script seems to only get external sharing on files, not folders. On line 82 and 324, you check to see if the item is a folder. If it's a file, you call WriteToFile which gets the sharing permissions on the item and writes it out to the CSV file. When it's a folder, you skip checking the sharing permissions on the folder and just expand the folder. Since it's possible to share folders as well as files, I think the script should also call writeToFile for the folders as well so that the report can include external sharing performed on folders as well.

**Comment by smcavinue** [comment]
Good catch, do you have a resolution alread? You could create a pull request

**Comment by Delsk** [comment]
sorry, I didn't catch your response to this one. The only thing I changed to get this to work IIRC is to add the "writeTofile -file $item -filepath $filePath" after line 85.
