### ISSUE TITLE
MX and Connector settings

### ISSUE THREAD

**Issue by andypituch** [smcavinue/AdminSeanMc#8]
Hi Sean!

Can you add the "testmode" attribute to connectors since you choose to return test mode connectors in the script (which is a good idea), we should have a way to filter them. I edited by clone of the script to include the column and sort on it, then whether the connector is enabled so all active connectors are grouped together, but I can see them all in the worksheet.

_$OutboundConnectors = Get-OutboundConnector -IncludeTestModeConnectors:$true | Sort-Object TestMode, enabled, name | Select-Object **TestMode**, enabled, name, connectortype, connectorsource, TLSSettings, RecipientDomains, UseMXRecord, SmartHosts, Comment_

For MX records, adding an additional filter when obtaining the MX record via resolve-DNS name will prevent the additional A records from being returned (or SOA in the case of no MX record being present). I edited my copy to return only the MX records then to sort them on preference and the nameExchange

[array]$MXRecords = Resolve-DnsName -Name $domain.name -Type mx -ErrorAction SilentlyContinue | **Where-Object { $_.type -eq "MX" } | Sort-Object preference, nameexchange**

**Comment by smcavinue** [comment]
That would be good, I'll add it to my list for the next version or you could create a pull request
